import 'dart:math';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/arena_models.dart';

class ArenaRoomRepository {
  final FirebaseFirestore _firestore;

  ArenaRoomRepository(this._firestore);

  CollectionReference<Map<String, dynamic>> get _roomsRef =>
      _firestore.collection('arena_rooms');

  Future<String> createRoom({
    required ArenaPlayer host,
    required ArenaConfig config,
  }) async {
    String roomCode = '';
    bool isUnique = false;
    int attempts = 0;

    while (!isUnique && attempts < 10) {
      roomCode = (10000 + Random().nextInt(90000)).toString();
      final existing =
          await _roomsRef
              .where('roomCode', isEqualTo: roomCode)
              .where('status', isNotEqualTo: 'finished')
              .limit(1)
              .get();
      if (existing.docs.isEmpty) {
        isUnique = true;
      }
      attempts++;
    }

    if (!isUnique) throw Exception('Failed to generate unique room code');

    final docRef = _roomsRef.doc();
    // Create room with minimal initial data.
    // Note: We use toJson() which will be generated by freezed/json_serializable
    // Ensure DateTime is converted properly (using the converter we added).

    final room = ArenaRoom(
      id: docRef.id,
      roomCode: roomCode,
      status: ArenaStatus.waiting,
      hostId: host.id,
      config: config,
      host: host,
      createdAt: DateTime.now(),
    );

    await docRef.set(room.toJson());
    return docRef.id;
  }

  Future<String> joinRoom({
    required String roomCode,
    required ArenaPlayer guest,
  }) async {
    final query =
        await _roomsRef
            .where('roomCode', isEqualTo: roomCode)
            .where('status', isEqualTo: 'waiting')
            .limit(1)
            .get();

    if (query.docs.isEmpty) {
      throw Exception('Room not found or not available');
    }

    final docRef = query.docs.first.reference;

    await _firestore.runTransaction((transaction) async {
      final snapshot = await transaction.get(docRef);
      if (!snapshot.exists) throw Exception('Room does not exist');

      final roomData = snapshot.data()!;
      if (roomData['guestId'] != null) {
        throw Exception('Room is full');
      }

      transaction.update(docRef, {
        'guestId': guest.id,
        'guest': guest.toJson(),
      });
    });

    return docRef.id;
  }

  Stream<ArenaRoom?> watchRoom(String roomId) {
    return _roomsRef.doc(roomId).snapshots().map((snapshot) {
      if (!snapshot.exists) return null;
      return ArenaRoom.fromJson(snapshot.data()!);
    });
  }

  Future<void> updateStatus(String roomId, ArenaStatus status) async {
    // Enum serialization depends on generated code. Assuming string here.
    // If json_serializable is used, it defaults to string.
    await _roomsRef.doc(roomId).update({'status': status.name});
  }

  Future<void> startMatch(
    String roomId,
    ArenaRound round,
    ResolvedWorksheet resolvedWorksheet,
  ) async {
    await _roomsRef.doc(roomId).update({
      'status': 'active', // ArenaStatus.active.name
      'round': round.toJson(),
      'resolvedWorksheet': resolvedWorksheet.toJson(),
    });
  }

  Future<void> updateScores(
    String roomId,
    int hostScore,
    int guestScore,
  ) async {
    await _roomsRef.doc(roomId).update({
      'hostScore': hostScore,
      'guestScore': guestScore,
    });
  }

  Future<void> updatePlayerPresence(String roomId, String userId, bool isHost) async {
    final field = isHost ? 'host' : 'guest';
    await _roomsRef.doc(roomId).update({
      '$field.lastPing': FieldValue.serverTimestamp(),
      '$field.isOnline': true,
    });
  }

  Future<void> updateConfig(String roomId, ArenaConfig config) async {
    await _roomsRef.doc(roomId).update({
      'config': config.toJson(),
    });
  }
}
