# Isar Database ProGuard Rules
# Isar uses native libraries and reflection, so we need to preserve these classes

# Keep all native methods (CRITICAL for Isar - it uses JNI)
-keepclasseswithmembernames class * {
    native <methods>;
}

# Keep native methods even if they appear unused
-keepclasseswithmembernames,allowshrinking,allowobfuscation class * {
    native <methods>;
}

# Keep all annotations (Isar uses annotations for schema)
-keepattributes *Annotation*
-keepattributes Signature
-keepattributes Exceptions
-keepattributes InnerClasses
-keepattributes EnclosingMethod
-keepattributes SourceFile
-keepattributes LineNumberTable

# Keep Flutter embedding and plugins (including Isar Flutter plugin)
-keep class io.flutter.embedding.** { *; }
-keep class io.flutter.plugins.** { *; }

# Keep Isar Flutter libs native wrapper
-keep class dev.xxf.isar.flutter.** { *; }

# Keep all generated Isar schema and collection code
-keep class **$$isar { *; }
-keep class *$IsarSchema { *; }
-keep class *Schema { *; }
-keep class **CollectionSchema { *; }
-keep class **PropertySchema { *; }
-keep class **Collection** { *; }

# Keep ALL extension classes (critical for Isar collections)
# Extension classes: GetWordSetCollection, GetWordPairCollection, GetDictEntryCollection
-keep class **Get*Collection* { *; }
-keep class **GetWordSetCollection { *; }
-keep class **GetWordPairCollection { *; }
-keep class **GetDictEntryCollection { *; }

# Keep extension getters (wordSets, wordPairs, dictEntrys)
-keepclassmembers class **Get*Collection* {
    IsarCollection<*> get wordSets;
    IsarCollection<*> get wordPairs;
    IsarCollection<*> get dictEntrys;
}

# Keep ALL classes with "Collection" in name (Isar generated)
-keep class **Collection { *; }
-keep class **CollectionSchema { *; }

# Don't obfuscate native library classes
-keepnames class ** {
    native <methods>;
}

# Preserve class names that might be accessed via JNI
-keepnames class ** { *; }

# Don't warn about missing classes
-dontwarn dev.xxf.isar.**
-dontwarn io.flutter.plugins.**

# Google Play Core classes (used by Flutter deferred components - optional dependency)
# These are optional and not needed if not using deferred components
# Auto-generated by R8 - add these rules to suppress warnings
-dontwarn com.google.android.play.core.splitcompat.SplitCompatApplication
-dontwarn com.google.android.play.core.splitinstall.SplitInstallException
-dontwarn com.google.android.play.core.splitinstall.SplitInstallManager
-dontwarn com.google.android.play.core.splitinstall.SplitInstallManagerFactory
-dontwarn com.google.android.play.core.splitinstall.SplitInstallRequest$Builder
-dontwarn com.google.android.play.core.splitinstall.SplitInstallRequest
-dontwarn com.google.android.play.core.splitinstall.SplitInstallSessionState
-dontwarn com.google.android.play.core.splitinstall.SplitInstallStateUpdatedListener
-dontwarn com.google.android.play.core.tasks.OnFailureListener
-dontwarn com.google.android.play.core.tasks.OnSuccessListener
-dontwarn com.google.android.play.core.tasks.Task

# Flutter deferred components (Play Store split install)
-dontwarn io.flutter.embedding.engine.deferredcomponents.PlayStoreDeferredComponentManager

# General Flutter/Dart interop preservation
-keep class io.flutter.view.** { *; }
-keep class io.flutter.util.** { *; }
-keep class io.flutter.embedding.** { *; }

# Google Sign-In ProGuard Rules
-keep class com.google.android.gms.** { *; }
-dontwarn com.google.android.gms.**
-keep class com.google.api.client.** { *; }
-keep class com.google.auth.** { *; }
-keep class com.google.common.** { *; }
-dontwarn com.google.common.**
-keep class com.google.gson.** { *; }
-keep class com.google.oauth.** { *; }

# Keep Google Sign-In classes
-keep class com.google.android.gms.auth.** { *; }
-keep class com.google.android.gms.common.** { *; }
-keep class com.google.android.gms.tasks.** { *; }

# Firebase Auth
-keep class com.google.firebase.auth.** { *; }
-dontwarn com.google.firebase.auth.**
